[package]
name = "winrt"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = "0.2.1"

[dependencies.windows]
version = "0.58.0"
features = [
    "Foundation", 
    "Media_Control",
    "Media_Devices"
]
